Repository shoppingmall-page-study/Shoppingmall_Project_BackEnd, pull requests merged in 2023-03, with the labels that each got.

#136 레디스 서비스 반환 값 메서드 수정
  src/main/java/com/project/shopping/security/Tokenprovider.java
  src/main/java/com/project/shopping/service/EmailAuthenticationService.java
  src/main/java/com/project/shopping/service/RedisService.java
  src/main/java/com/project/shopping/service/RefreshTokenService.java
Labels: enhancement

#134 필요없는 메시지변수 삭제, authentication관련 컨트롤러 예외 제거
  src/main/java/com/project/shopping/Error/CustomException.java
  src/main/java/com/project/shopping/Error/GlobalExceptionHandler.java
  src/main/java/com/project/shopping/auth/PrinciplaDetailsService.java
  src/main/java/com/project/shopping/controller/CartController.java
  src/main/java/com/project/shopping/controller/ProductController.java
  src/main/java/com/project/shopping/controller/ReviewController.java
  src/main/java/com/project/shopping/controller/UserController.java
  src/main/java/com/project/shopping/security/JwtAuthorizationFilter.java
  src/main/java/com/project/shopping/security/Tokenprovider.java
  src/main/java/com/project/shopping/service/CartService.java
  src/main/java/com/project/shopping/service/EmailAuthenticationService.java
  src/main/java/com/project/shopping/service/OrderService.java
  src/main/java/com/project/shopping/service/PaymentService.java
  src/main/java/com/project/shopping/service/ProductService.java
  src/main/java/com/project/shopping/service/RedisService.java
  src/main/java/com/project/shopping/service/RefreshTokenService.java
  src/main/java/com/project/shopping/service/ReviewService.java
  src/main/java/com/project/shopping/service/UserService.java
Labels: bug, enhancement

#142 redisService 제거 후 각 class 마다 redisTemplate 사용 그리고 redis안에 저장된 Token 을…
  src/main/java/com/project/shopping/config/WebSecurityConfig.java
  src/main/java/com/project/shopping/controller/RefreshTokenController.java
  src/main/java/com/project/shopping/oauth/Oauth2SuccessHandler.java
  src/main/java/com/project/shopping/security/JwtAuthenticationFilter.java
  src/main/java/com/project/shopping/security/JwtAuthorizationFilter.java
  src/main/java/com/project/shopping/security/Token.java
  src/main/java/com/project/shopping/security/TokenProvider.java
  src/main/java/com/project/shopping/service/EmailAuthenticationService.java
  src/main/java/com/project/shopping/service/ProductService.java
  src/main/java/com/project/shopping/service/RedisService.java
  src/main/java/com/project/shopping/service/RefreshTokenService.java
Labels: enhancement, invalid

#145 사용 안하는 메서드 제거 및 변수명 수정
  src/main/java/com/project/shopping/controller/CartController.java
  src/main/java/com/project/shopping/controller/ProductController.java
  src/main/java/com/project/shopping/controller/ReviewController.java
  src/main/java/com/project/shopping/service/CartService.java
  src/main/java/com/project/shopping/service/PaymentService.java
  src/main/java/com/project/shopping/service/ProductService.java
Labels: invalid

#148 오아스 회원 가입시 refresh 토큰 쿠키 저장
  src/main/java/com/project/shopping/auth/PrincipalDetails.java
  src/main/java/com/project/shopping/config/WebMvcConfig.java
  src/main/java/com/project/shopping/config/WebSecurityConfig.java
  src/main/java/com/project/shopping/oauth/CustomOAuth2UserService.java
  src/main/java/com/project/shopping/oauth/Oauth2SuccessHandler.java
  src/main/java/com/project/shopping/security/TokenProvider.java
  src/main/java/com/project/shopping/service/UserService.java
Labels: invalid

#154 리뷰관련 도메인 authentication 수정
  src/main/java/com/project/shopping/controller/ReviewController.java
  src/main/java/com/project/shopping/service/ReviewService.java
Labels: bug, enhancement

#157 권한 이넘 클래스 생성 후 오아스로 첫 로그인시 추가 정보 받기
  src/main/java/com/project/shopping/auth/PrincipalDetails.java
  src/main/java/com/project/shopping/config/WebSecurityConfig.java
  src/main/java/com/project/shopping/controller/UserController.java
  src/main/java/com/project/shopping/dto/requestDTO/UserRequestDTO/UserOAuthAddInfoRequestDTO.java
  src/main/java/com/project/shopping/dto/responseDTO/UserResponseDTO/UserOAuthAddInfoResponseDTO.java
  src/main/java/com/project/shopping/model/User.java
  src/main/java/com/project/shopping/oauth/Oauth2SuccessHandler.java
  src/main/java/com/project/shopping/oauth/UserRequstMapper.java
  src/main/java/com/project/shopping/security/Role.java
  src/main/java/com/project/shopping/service/EmailAuthenticationService.java
  src/main/java/com/project/shopping/service/UserService.java
Labels: enhancement, invalid

#159 유저 컨트롤러 테스트 작성 중
  src/main/java/com/project/shopping/ShoppingApplication.java
  src/main/java/com/project/shopping/config/JpaAuditingConfiguration.java
  src/main/java/com/project/shopping/controller/UserController.java
  src/main/java/com/project/shopping/dto/requestDTO/UserRequestDTO/UserJoinRequestDTO.java
  src/main/java/com/project/shopping/service/EmailAuthenticationService.java
  src/main/java/com/project/shopping/service/UserService.java
  src/test/java/com/project/shopping/auth/WithMockCustomUser.java
  src/test/java/com/project/shopping/auth/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/project/shopping/config/TestConfig.java
  src/test/java/com/project/shopping/controller/UserControllerTest.java
  src/test/java/com/project/shopping/repository/UserRepositoryTest.java
  src/test/java/com/project/shopping/service/EmailAuthenticationServiceTest.java
  src/test/java/com/project/shopping/service/UserServiceTest.java
Labels: documentation, enhancement
